name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * 0
env:
  NAMESPACE: ${{ vars.NAMESPACE }}
  USERNAME: ${{ vars.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ vars.HOST }}
  DOCKER_NAMESPACE: ${{ vars.DH_NAMESPACE }}
  DOCKER_USERNAME: ${{ vars.DH_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DH_PASSWORD }}
  DOCKER_HOST: ${{ vars.DH_HOST }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        [ -z "$status" ]
    - name: ACR LOGIN
      run: docker login --username ${{ vars.USERNAME }} --password ${{ secrets.PASSWORD }}  ${{ vars.HOST }}
    - name: Docker Hub LOGIN
      run: docker login --username ${{ vars.DH_USERNAME }} --password ${{ secrets.DH_PASSWORD }}  ${{ vars.DH_HOST }}
    - name: Update the Docker image Version
      run:  ./update.sh
    - name: Build the Docker image
      run:  ./builds.sh
