name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * 0
env:
  NAMESPACE: ${{ vars.NAMESPACE }}
  USERNAME: ${{ vars.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ vars.HOST }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Apply Templates
    #   run: ./apply-templates.sh
    # - name: Check Git Status
    #   run: |
    #     status="$(git status --short)"
    #     [ -z "$status" ]
    - name: Docker Hub ACR LOGIN
      run: docker login --username ${{ vars.USERNAME }} --password ${{ secrets.PASSWORD }}  ${{ vars.HOST }}
    - name: Update the Docker image Version
      run:  ./update.sh
    - name: Build the Docker image
      run:  ./builds.sh
